### ISSUE TITLE
RE: One Question/Seth

### ISSUE THREAD

**Issue by silver2row** [e-ale/Slides#3]
Hello,

Besides all this great info, does the info. given work w/ a BBB, i.e. not the pocket Beagle?

Seth

**Comment by behanw** [comment]
> On Apr 1, 2018, at 3:45 AM, Seth <notifications@github.com> wrote:
> 
> Hello,
> 
> Besides all this great info, does the info. given work w/ a BBB, i.e. not the pocket Beagle?
> 

The info works is largely generic, so other than the most specific of details, it should work for all embedded boards.

Having said that, the same SW runs on both the BBB and PocketBeagle, since they use the same family of CPU and both use the reference TI design. Other than the headers, they’re basically the same boards.

The big difference, of course in our case, is that the baconbits board is largely what we’re driving in our exercises.

Behan
